name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  checks:
    uses: ./.github/workflows/check.yml

  release:
    needs: checks
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: BigWigsMods/packager@36b4c3b7b7bd17c835ad8c83fed4976c067edfbe
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
